# 3. 배열 생성 방법

In [9]:
import numpy as np

In [ ]:
# 리스트 → 배열
np.array([1, 2, 3])

array([1, 2, 3])

In [ ]:
# 특수 배열
np.zeros(5)
np.ones(5)
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

# 실습 1: 배열 생성

In [12]:
response_list = [120, 350, 95, 220, 180]
response_array = np.array(response_list)

print(response_list)
print(response_array)
print(type(response_array))

[120, 350, 95, 220, 180]
[120 350  95 220 180]
<class 'numpy.ndarray'>


# 실습 2: 특수 배열

In [13]:
# 0과 1로 채운 배열
print(np.zeros(5))
print(np.ones(5))
# 0과 1을 2차원으로 채우려면?
print(np.zeros([5,5]))
print(np.ones([5,5]))

# 연속된 수
print(np.arange(1, 10, 2))

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[1 3 5 7 9]


# 실습 3: 성능 비교

In [14]:
import time

lst = list(range(1000000))
arr = np.array(lst)

# 리스트 합
start = time.time()
sum([x*2 for x in lst])
print(time.time() - start)

# 배열 합
start = time.time()
(arr*2).sum()
print(time.time() - start)

0.08065176010131836
0.0070497989654541016


# 🔹 예시: 파이썬 vs NumPy 이미지 처리 속도

In [15]:
# 가짜 이미지
img = (np.random.rand(768, 1024, 3) * 255).astype(np.uint8)

# --- 파이썬 방식 (루프) ---
start = time.time()

gray_py = [[int(0.299*r + 0.587*g + 0.114*b) for r,g,b in row]for row in img]
print(time.time() - start)

# --- numpy 방식 (벡터 연산) ---
start = time.time()
gray_np = np.dot(img[...,:3], [0.299, 0.587, 0.114])
print(time.time() - start)

7.097699165344238
0.023438215255737305


# 2교시: 배열 속성과 탐색

In [16]:
# 1. 배열의 속성

arr = np.array([[1,2,3],[4,5,6]])
print(arr.ndim)
print(arr. shape)
print(arr.size)
print(arr.dtype)

2
(2, 3)
6
int64


In [19]:
# 2. 인덱싱(Indexing)
# 1차원 배열
arr = np.array([10,20,30])
print(arr[0])

# 2차원 배열
arr = np.array([[10,20,30],[40,50,60]])
print(arr[1,2])

10
60


In [21]:
# 3. 슬라이싱(Slicing)
# 1차원 배열 예제

arr = np.array([10, 20, 30, 40, 50, 60, 70])

# 기본 슬라이싱
print(arr[1:4])
print(arr[:3])
print(arr[4:])

# 간격(step) 사용
print(arr[::2])
print(arr[1::2])
print(arr[::-1])

# 특정 구간 역순
print(arr[5:2:-1])

[20 30 40]
[10 20 30]
[50 60 70]
[10 30 50 70]
[20 40 60]
[70 60 50 40 30 20 10]
[60 50 40]


In [24]:
# 2차원 배열 예제
mat = np.array([[1,2,3],
               [4,5,6],
               [7,8,9],
               [10,11,12]])

# 행 선택
print(mat[0:2])
print(mat[::2])

# 열 선택
print(mat[:, 1:3])

# 행, 열 동시에
print(mat[1:3, 0:2])

# 부분 선택 + 간격
print(mat[::2, ::2])

# 역순
print(mat[::-1])
print(mat[:, ::-1])

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [7 8 9]]
[[ 2  3]
 [ 5  6]
 [ 8  9]
 [11 12]]
[[4 5]
 [7 8]]
[[1 3]
 [7 9]]
[[10 11 12]
 [ 7  8  9]
 [ 4  5  6]
 [ 1  2  3]]
[[ 3  2  1]
 [ 6  5  4]
 [ 9  8  7]
 [12 11 10]]


In [29]:
# 4. 조건 인덱싱(Boolean Indexing)

#  1개의 조건
arr = np.array([10, 20, 30, 40, 50, 60, 70])

print(arr[arr > 30])
print(arr[arr <= 40])
print(arr[arr % 20 == 0])

[40 50 60 70]
[10 20 30 40]
[20 40 60]


In [33]:
 # 2개의 조건 (AND: &, OR: |)

# AND 조건 
print(arr[(arr > 20) & (arr < 60)])

# OR 조건
print(arr[(arr < 25) | (arr > 55)])

# NOT 조건
print(arr[~(arr % 30 == 0)])

[30 40 50]
[10 20 60 70]
[10 20 40 50 70]


In [34]:
# 2차원 배열 조건 인덱싱
mat = np.array([[1,2,3],
                [4,5,6],
                [7,8,9],
                [10,11,12]])

print(mat[mat > 5])
print(mat[(mat % 2 == 0)])

# 2개 조건 (예: 5 이상 AND 10 이하)
print(mat[(mat >= 5) & (mat <= 10)])

[ 6  7  8  9 10 11 12]
[ 2  4  6  8 10 12]
[ 5  6  7  8  9 10]


In [35]:
# 실습 1: 배열 속성 확인

response_array = np.array([[120, 350, 95],
                           [220, 180, 140]])

print(response_array.ndim)
print(response_array.shape)
print(response_array.size)
print(response_array.dtype)

2
(2, 3)
6
int64


In [36]:
# 실습 2: 인덱싱
# 2차원 배열에서 특정 값 추출
print(response_array[0,1])
print(response_array[1])

350
[220 180 140]


In [37]:
# 실습 3: 슬라이싱

# 1차원 슬라이싱
arr = np.arange(10, 60, 10)
print(arr)
print(arr[1:4])

# 2차원 슬라이싱
print(response_array[0:2, 1:3])

[10 20 30 40 50]
[20 30 40]
[[350  95]
 [180 140]]


In [39]:
# 실습 4: 조건 인덱싱
# 200ms 이상 응답만 추출
print(response_array[response_array >= 200])
# 짝수 응답시간만 추출
print(response_array[response_array % 2 == 0])

[350 220]
[120 350 220 180 140]


# 3교시: 조건 필터링 & 브로드캐스팅

In [40]:
# 1. 조건 필터링(Boolean Indexing)
arr = np.array([120, 350, 95, 220, 180])
print(arr > 200)
print(arr[arr > 200])

print(arr[arr <= 180])

[False  True False  True False]
[350 220]
[120  95 180]


In [41]:
# 2. 복합 조건
# 150 이상 AND 300 이하
print(arr[(arr >= 150) & (arr <= 300)])

# 100 미만 OR 300 초과
print(arr[(arr < 100) | (arr > 300)])

# NOT(200 이하 값만)
print(arr[~(arr > 200)])


[220 180]
[350  95]
[120  95 180]


In [42]:
# 3. 브로드캐스팅(Broadcasting)
arr = np.array([1,2,3,4,5])
print(arr + 10)

[11 12 13 14 15]


In [43]:
# 2차원 배열도 마찬가지

mat = np.array([[1,2,3],
                [4,5,6]])
print(mat + np.array([10,20,30]))

[[11 22 33]
 [14 25 36]]


In [44]:
# 실습 1: 조건 필터링
response_array = np.array([120, 350, 95, 220, 180, 510])

# 200ms 이상 요청만 추출
response_array = np.array([response_array  >= 200])

# 100~300ms 사이만 추출
print(response_array[(response_array >= 100) & (response_array <= 300)])

[]


In [45]:
# 실습 2: 조건 + 통계

# 느린 요청 비율 계산
slow_rate = (response_array > 400).mean()
print(slow_rate)

0.0


In [47]:
# 실습 3: 브로드캐스팅

# 응답시간 배열에 50ms 네트워크 지연 추가 
adjusted = response_array + 50
print(adjusted)

# 2차원 배열 브로드캐스팅
mat = np.array([[100,200,300],
                [400,500,600]])
penalty = np.array([10,20,30])
print(mat + penalty)

[[50 51 50 51 50 51]]
[[110 220 330]
 [410 520 630]]


# 4교시: 수학 연산과 통계

In [48]:
# 1. 기본 산술 연산

arr = np.array([10, 20, 30])

# 덧셈
print(arr + 5)
# 뺄셈
print(arr - 5)
# 곱셈
print(arr * 2)
# 나눗셈
print(arr / 2)
# 제곱
print(arr ** 2)

# 원소간의 계산
arr1 = np.array([1,2,3])
arr2 = np.array([10, 20, 30])

# 원소별 덧셈/곱셈
print(arr1 + arr2)
print(arr1 * arr2)

[15 25 35]
[ 5 15 25]
[20 40 60]
[ 5. 10. 15.]
[100 400 900]
[11 22 33]
[10 40 90]


In [49]:
# 2. 통계 함수

arr = np.array([120, 350, 95, 220, 180])

print(arr.sum())
print(arr.prod)
print(arr.mean())
print(arr.std())
print(arr.var())
print(arr.min())
print(arr.max())
print(np.median(arr))

965
<built-in method prod of numpy.ndarray object at 0x000001ADF9236130>
193.0
89.97777503361594
8096.0
95
350
180.0


In [51]:
# [2차원 계산]

mat = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print(mat.sum())
print(mat.sum(axis=1))
print(mat.sum(axis=0))

print(mat.mean(axis=1))
print(mat.max(axis=0))

45
[ 6 15 24]
[12 15 18]
[2. 5. 8.]
[7 8 9]


In [52]:
# 3. 행렬 연산

mat = np.array([[1,2],[3,4]])
vec = np.array([10,20])
print(mat.T)
print(np.dot(mat, vec))

[[1 3]
 [2 4]]
[ 50 110]


In [53]:
mat = np.array([[1, 2, 3],
                [4, 5, 6]])
print(mat.shape)
print(mat.T.shape)

(2, 3)
(3, 2)


In [54]:
# 실습 1: 기본 연산

response_array = np.array([120, 350, 95, 220, 180])

print(response_array + 10)
print(response_array * 2)

[130 360 105 230 190]
[240 700 190 440 360]


In [55]:
# 실습 3: 느린 요청 분석

# 200ms 이상 응답의 평균
slow_requests = response_array[response_array >= 200]
print(slow_requests.mean())

# 95% 분위수 (성능 SLA 기준으로 활용)
p95 = np.percentile(response_array, 95)
print(p95)

285.0
324.0


In [ ]:
# 실습 4: 행렬 연산

# 사용자 x 엔드포인트 응답시간 매트릭스
mat = np.array([[120, 350, 95],
                [200, 180, 140],
                [410, 290, 330]])

print(mat.T)
